### ISSUE TITLE
An extra dot in the notification bar, when activating a patch

### ISSUE THREAD

**Issue by tuplasuhveli** [sailfishos-patches/patchmanager#466]
**SailfishOS VERSION** (Settings → About product → Build):  4.6.0.15
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Sony Xperia 10 V
<br />**PATCHMANAGER VERSION** (Settings → Patchmanager → \<Top pulley\> → About): 3.2.11
<br />

#### BUG DESCRIPTION

The notification bar contains an extra dot, at least in English (UK) UI, when user activates a patch. See the screenshot below in the additional information section.

#### STEPS TO REPRODUCE

1. Have a patch installed
2. Activate the patch
3. Take a look at the notification bar

#### ADDITIONAL INFORMATION

![patchmanager_notification](https://github.com/user-attachments/assets/ed083c21-391e-48ef-9c61-b2d022785b6d)

**Comment by Olf0** [comment]
Thank you for your bug report.  Yes, this looks like a simple oversight, because [the logic is already there](https://github.com/sailfishos-patches/patchmanager/blob/master/src/bin/patchmanager-daemon/patchmanagerobject.cpp#L276-L286): When `some service(s) should be restarted.` is not appended, it this notification should be ultimately wrongly concluded with two full stops, i.e. `Patch %1 activated..`.

I addressed this in PR #467.
